[log_clients]
log-client01 ansible_host=192.168.0.106 ansible_user=ubuntu

[kafka]
kafka01 ansible_host=192.168.0.160 ansible_user=ubuntu

[logstash]
logstash01 ansible_host=192.168.0.161 ansible_user=ubuntu

[opensearch]
search01 ansible_host=192.168.0.162 ansible_user=ubuntu

[dashboards]
dashboard01 ansible_host=192.168.0.163 ansible_user=ubuntu