[web]
web-01 ansible_host=192.168.0.101 ansible_user=ubuntu backend_name=web-01
web-02 ansible_host=192.168.0.102 ansible_user=ubuntu backend_name=web-02

[lb]
lb-01 ansible_host=192.168.0.201 ansible_user=ubuntu keepalived_state=MASTER keepalived_priority=150
lb-02 ansible_host=192.168.0.202 ansible_user=ubuntu keepalived_state=BACKUP keepalived_priority=100

[ha_lab:children]
web
lb
