[postgres]
pg-01 ansible_host=192.168.0.151 ansible_user=ubuntu patroni_name=pg-01
pg-02 ansible_host=192.168.0.152 ansible_user=ubuntu patroni_name=pg-02
pg-03 ansible_host=192.168.0.153 ansible_user=ubuntu patroni_name=pg-03

[etcd]
etcd-01 ansible_host=192.168.0.161 ansible_user=ubuntu etcd_name=etcd-01
etcd-02 ansible_host=192.168.0.162 ansible_user=ubuntu etcd_name=etcd-02
etcd-03 ansible_host=192.168.0.163 ansible_user=ubuntu etcd_name=etcd-03

[haproxy]
pg-lb-01 ansible_host=192.168.0.171 ansible_user=ubuntu